made some small changes to bashrc, auto tmux on ssh

diff --git a/configs/bashrc b/configs/bashrc
--- a/configs/bashrc
+++ b/configs/bashrc
@@ -77,9 +77,25 @@ alias ls='ls -Gp'
 alias grep='grep --color=auto'  
 #
 
+
+####################################################################################################
+# Auto start tmux if ssh ###########################################################################
+####################################################################################################
+
+if [ "$PS1" != "" -a "${STARTED_TMUX:-x}" = x -a "${SSH_TTY:-x}" != x ]
+then
+        STARTED_TMUX=1; export STARTED_TMUX
+        sleep 1
+        ( (tmux has-session -t remote && tmux attach-session -t remote) || (tmux new-session -s remote) ) && exit 0
+        echo "tmux failed to start"
+fi
+#
+
 ####################################################################################################
 # For rvm & ruby paths #############################################################################
 ####################################################################################################
+
+#
 
 fi
   
